Repository ianarsenault/Pulse-Roshambo, pull requests merged in 2018-03, with the labels that each got.

#27 Added a tab index on the add new player button
  client/src/components/NewPlayer.vue
Labels: bug

#36 Leaderboard endpoints, services, and saving of each game
  README.md
  client/package-lock.json
  client/package.json
  client/src/components/EditPlayer.vue
  client/src/components/GameLogs.vue
  client/src/components/Leaderboard.vue
  client/src/components/Navigation.vue
  client/src/components/PlayerProfile.vue
  client/src/components/Players.vue
  client/src/router/index.js
  client/src/services/BattleEngine.js
  client/src/services/GameLogsService.js
  server/models/GameLogs.js
  server/models/gamelogs.js
  server/routes/gamelogs.js
  server/src/app.js
Labels: enhancement, feature

#38 sort date to show most recent games first
  client/src/components/GameLogs.vue
Labels: enhancement

#39 BUG: GameLog no longer displays current date, but rather date of game
  client/src/components/GameLogs.vue
  client/src/services/BattleEngine.js
Labels: bug

#44 Loading Animation
  client/src/components/GameLogs.vue
  client/src/components/LoadingIndicator.vue
  client/src/components/Players.vue
Labels: enhancement
